.TH "HUGO\-IMPORT\-JEKYLL" "1" "Apr 2017" "Hugo 0.18.1" "Hugo Manual" 
.nh
.ad l


.SH NAME
.PP
hugo\-import\-jekyll \- hugo import from Jekyll


.SH SYNOPSIS
.PP
\fBhugo import jekyll\fP


.SH DESCRIPTION
.PP
hugo import from Jekyll.

.PP
Import from Jekyll requires two paths, e.g. \fB\fChugo import jekyll jekyll\_root\_path target\_path\fR\&.


.SH OPTIONS
.PP
\fB\-\-force\fP[=false]
    Allow import into non\-empty target directory


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
    config file (default is path/config.yaml|json|toml)

.PP
\fB\-\-log\fP[=false]
    Enable Logging

.PP
\fB\-\-logFile\fP=""
    Log File path (if set, logging enabled automatically)

.PP
\fB\-\-quiet\fP[=false]
    build in quiet mode

.PP
\fB\-v\fP, \fB\-\-verbose\fP[=false]
    verbose output

.PP
\fB\-\-verboseLog\fP[=false]
    verbose logging


.SH SEE ALSO
.PP
\fBhugo\-import(1)\fP
