.TH "HUGO\-IMPORT" "1" "Apr 2017" "Hugo 0.18.1" "Hugo Manual" 
.nh
.ad l


.SH NAME
.PP
hugo\-import \- Import your site from others.


.SH SYNOPSIS
.PP
\fBhugo import\fP


.SH DESCRIPTION
.PP
Import your site from other web site generators like Jekyll.

.PP
Import requires a subcommand, e.g. \fB\fChugo import jekyll jekyll\_root\_path target\_path\fR\&.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
    config file (default is path/config.yaml|json|toml)

.PP
\fB\-\-log\fP[=false]
    Enable Logging

.PP
\fB\-\-logFile\fP=""
    Log File path (if set, logging enabled automatically)

.PP
\fB\-\-quiet\fP[=false]
    build in quiet mode

.PP
\fB\-v\fP, \fB\-\-verbose\fP[=false]
    verbose output

.PP
\fB\-\-verboseLog\fP[=false]
    verbose logging


.SH SEE ALSO
.PP
\fBhugo(1)\fP, \fBhugo\-import\-jekyll(1)\fP
