.TH "HUGO\-GEN" "1" "Apr 2017" "Hugo 0.18.1" "Hugo Manual" 
.nh
.ad l


.SH NAME
.PP
hugo\-gen \- A collection of several useful generators.


.SH SYNOPSIS
.PP
\fBhugo gen\fP


.SH DESCRIPTION
.PP
A collection of several useful generators.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
    config file (default is path/config.yaml|json|toml)

.PP
\fB\-\-log\fP[=false]
    Enable Logging

.PP
\fB\-\-logFile\fP=""
    Log File path (if set, logging enabled automatically)

.PP
\fB\-\-quiet\fP[=false]
    build in quiet mode

.PP
\fB\-v\fP, \fB\-\-verbose\fP[=false]
    verbose output

.PP
\fB\-\-verboseLog\fP[=false]
    verbose logging


.SH SEE ALSO
.PP
\fBhugo(1)\fP, \fBhugo\-gen\-autocomplete(1)\fP, \fBhugo\-gen\-doc(1)\fP, \fBhugo\-gen\-man(1)\fP
