.TH "HUGO\-LIST" "1" "Apr 2017" "Hugo 0.18.1" "Hugo Manual" 
.nh
.ad l


.SH NAME
.PP
hugo\-list \- Listing out various types of content


.SH SYNOPSIS
.PP
\fBhugo list\fP


.SH DESCRIPTION
.PP
Listing out various types of content.

.PP
List requires a subcommand, e.g. \fB\fChugo list drafts\fR\&.


.SH OPTIONS
.PP
\fB\-s\fP, \fB\-\-source\fP=""
    filesystem path to read files relative from


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
    config file (default is path/config.yaml|json|toml)

.PP
\fB\-\-log\fP[=false]
    Enable Logging

.PP
\fB\-\-logFile\fP=""
    Log File path (if set, logging enabled automatically)

.PP
\fB\-\-quiet\fP[=false]
    build in quiet mode

.PP
\fB\-v\fP, \fB\-\-verbose\fP[=false]
    verbose output

.PP
\fB\-\-verboseLog\fP[=false]
    verbose logging


.SH SEE ALSO
.PP
\fBhugo(1)\fP, \fBhugo\-list\-drafts(1)\fP, \fBhugo\-list\-expired(1)\fP, \fBhugo\-list\-future(1)\fP
