.TH "HUGO\-GEN\-MAN" "1" "Apr 2017" "Hugo 0.18.1" "Hugo Manual" 
.nh
.ad l


.SH NAME
.PP
hugo\-gen\-man \- Generate man pages for the Hugo CLI


.SH SYNOPSIS
.PP
\fBhugo gen man\fP


.SH DESCRIPTION
.PP
This command automatically generates up\-to\-date man pages of Hugo's
command\-line interface.  By default, it creates the man page files
in the "man" directory under the current directory.


.SH OPTIONS
.PP
\fB\-\-dir\fP="man/"
    the directory to write the man pages.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
    config file (default is path/config.yaml|json|toml)

.PP
\fB\-\-log\fP[=false]
    Enable Logging

.PP
\fB\-\-logFile\fP=""
    Log File path (if set, logging enabled automatically)

.PP
\fB\-\-quiet\fP[=false]
    build in quiet mode

.PP
\fB\-v\fP, \fB\-\-verbose\fP[=false]
    verbose output

.PP
\fB\-\-verboseLog\fP[=false]
    verbose logging


.SH SEE ALSO
.PP
\fBhugo\-gen(1)\fP
