.TH "HUGO\-ENV" "1" "Apr 2017" "Hugo 0.18.1" "Hugo Manual" 
.nh
.ad l


.SH NAME
.PP
hugo\-env \- Print Hugo version and environment info


.SH SYNOPSIS
.PP
\fBhugo env\fP


.SH DESCRIPTION
.PP
Print Hugo version and environment info. This is useful in Hugo bug reports.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
    config file (default is path/config.yaml|json|toml)

.PP
\fB\-\-log\fP[=false]
    Enable Logging

.PP
\fB\-\-logFile\fP=""
    Log File path (if set, logging enabled automatically)

.PP
\fB\-\-quiet\fP[=false]
    build in quiet mode

.PP
\fB\-v\fP, \fB\-\-verbose\fP[=false]
    verbose output

.PP
\fB\-\-verboseLog\fP[=false]
    verbose logging


.SH SEE ALSO
.PP
\fBhugo(1)\fP
